export const ARTICLE_SITE_DOMAINS = [
  // ── Philippine News ────────────────────────────────────────────────────────
  'gmanetwork.com',
  'abs-cbn.com',
  'abscbn.com',
  'philstar.com',
  'inquirer.net',
  'rappler.com',
  'manilabulletin.com',
  'mb.com.ph',
  'manilatimes.net',
  'sunstar.com.ph',
  'businessmirror.com.ph',
  'businessworld.com.ph',
  'pna.gov.ph',
  'cnnphilippines.com',
  'interaksyon.com',
  'philnews.ph',
  'malaya.com.ph',
  'tempo.com.ph',
  'mindanews.com',
  'panay-news.com',
  'cebudailynews.inquirer.net',
  'cebuano.gmanetwork.com',
  'uno.inquirer.net',
  'panaynews.net',

  // ── US News ────────────────────────────────────────────────────────────────
  'cnn.com',
  'nytimes.com',
  'washingtonpost.com',
  'usatoday.com',
  'nbcnews.com',
  'cbsnews.com',
  'abcnews.go.com',
  'foxnews.com',
  'npr.org',
  'apnews.com',
  'reuters.com',
  'newsweek.com',
  'time.com',
  'theatlantic.com',
  'huffpost.com',
  'politico.com',
  'axios.com',
  'vox.com',
  'slate.com',
  'salon.com',
  'thehill.com',
  'motherjones.com',
  'thenation.com',
  'newrepublic.com',
  'propublica.org',
  'msnbc.com',
  'nypost.com',
  'chicagotribune.com',
  'latimes.com',
  'bostonglobe.com',
  'sfchronicle.com',
  'denverpost.com',
  'seattletimes.com',
  'dallasnews.com',
  'houstonchronicle.com',
  'miamiheral.com',
  'tampabay.com',
  'startribune.com',
  'governing.com',

  // ── UK / European News ─────────────────────────────────────────────────────
  'bbc.com',
  'bbc.co.uk',
  'theguardian.com',
  'independent.co.uk',
  'telegraph.co.uk',
  'thetimes.co.uk',
  'ft.com',
  'economist.com',
  'spectator.co.uk',
  'newstatesman.com',
  'euronews.com',
  'dw.com',
  'france24.com',
  'lemonde.fr',
  'lefigaro.fr',
  'spiegel.de',
  'zeit.de',
  'elpais.com',
  'corriere.it',
  'repubblica.it',
  'nos.nl',
  'svt.se',
  'yle.fi',
  'rte.ie',
  'irishtimes.com',

  // ── Asia-Pacific News ──────────────────────────────────────────────────────
  'straitstimes.com',
  'channelnewsasia.com',
  'todayonline.com',
  'scmp.com',
  'japantimes.co.jp',
  'nikkei.com',
  'asahi.com',
  'yomiuri.co.jp',
  'koreatimes.co.kr',
  'koreaherald.com',
  'bangkokpost.com',
  'nationthailand.com',
  'thestar.com.my',
  'nst.com.my',
  'vietnamnews.vn',
  'vnexpress.net',
  'thejakartapost.com',
  'hindustantimes.com',
  'thehindu.com',
  'ndtv.com',
  'timesofindia.indiatimes.com',
  'indianexpress.com',
  'dawn.com',
  'thenews.com.pk',
  'bdnews24.com',
  'thedailystar.net',
  'sundaytimes.lk',
  'smh.com.au',
  'theage.com.au',
  'abc.net.au',
  'theguardian.com', // au edition shares domain
  'rnz.co.nz',
  'stuff.co.nz',
  'nzherald.co.nz',

  // ── Middle East / Africa ───────────────────────────────────────────────────
  'aljazeera.com',
  'arabnews.com',
  'gulf-times.com',
  'timesofisrael.com',
  'haaretz.com',
  'dailysabah.com',
  'egyptindependent.com',
  'dailymaverick.co.za',
  'news24.com',
  'allafrica.com',
  'thisisafrica.me',
  'thenewhumanitarian.org',

  // ── Latin America ──────────────────────────────────────────────────────────
  'infobae.com',
  'clarin.com',
  'lanacion.com.ar',
  'folha.uol.com.br',
  'g1.globo.com',
  'eluniversal.com',
  'excelsior.com.mx',
  'eltiempo.com',

  // ── Technology ────────────────────────────────────────────────────────────
  'techcrunch.com',
  'theverge.com',
  'wired.com',
  'engadget.com',
  'arstechnica.com',
  'zdnet.com',
  'cnet.com',
  'tomsguide.com',
  'tomshardware.com',
  'pcmag.com',
  'pcworld.com',
  'gizmodo.com',
  '9to5mac.com',
  '9to5google.com',
  'macrumors.com',
  'androidauthority.com',
  'xda-developers.com',
  'digitaltrends.com',
  'venturebeat.com',
  'techradar.com',
  'makeuseof.com',
  'howtogeek.com',
  'slashgear.com',
  'thenextweb.com',
  'techrepublic.com',
  'infoworld.com',
  'computerworld.com',
  'networkworld.com',
  'itpro.co.uk',
  'techmonitor.ai',
  'siliconrepublic.com',
  'protocol.com',
  'restofworld.org',

  // ── Business & Finance ────────────────────────────────────────────────────
  'bloomberg.com',
  'forbes.com',
  'wsj.com',
  'cnbc.com',
  'marketwatch.com',
  'fortune.com',
  'businessinsider.com',
  'inc.com',
  'entrepreneur.com',
  'fastcompany.com',
  'hbr.org',
  'qz.com',
  'thestreet.com',
  'investopedia.com',
  'barrons.com',
  'seekingalpha.com',

  // ── Science & Health ─────────────────────────────────────────────────────
  'scientificamerican.com',
  'nature.com',
  'science.org',
  'newscientist.com',
  'medicalnewstoday.com',
  'webmd.com',
  'healthline.com',
  'livescience.com',
  'space.com',
  'nationalgeographic.com',
  'discovermagazine.com',
  'popsci.com',
  'sciencedaily.com',
  'statnews.com',
  'theconversation.com',

  // ── Sports ────────────────────────────────────────────────────────────────
  'espn.com',
  'bleacherreport.com',
  'si.com',
  'cbssports.com',
  'nbcsports.com',
  'theathletic.com',
  'sportingnews.com',
  'goal.com',
  'skysports.com',
  'marca.com',

  // ── Entertainment ─────────────────────────────────────────────────────────
  'variety.com',
  'hollywoodreporter.com',
  'deadline.com',
  'ew.com',
  'rollingstone.com',
  'pitchfork.com',
  'vulture.com',
  'avclub.com',
  'collider.com',
  'screenrant.com',
  'indiewire.com',
  'theplaylist.net',
] as const;

export const isArticleSiteUrl = (url: string): boolean => {
  try {
    const { hostname } = new URL(url);
    return ARTICLE_SITE_DOMAINS.some(
      (domain) => hostname === domain || hostname.endsWith(`.${domain}`),
    );
  } catch {
    return false;
  }
};
