/**
 * Share metadata recording.
 *
 * Separate from `shareLink.ts` on purpose: that file only mints the id the
 * link carries and never touches the network. This file's only job is telling
 * the backend a share happened.
 *
 * The actual network call happens in the main process, via `shareBridge`
 * (see `core-app/ipc/main/shareHandler.ts`) — a renderer-side `fetch` to this
 * endpoint hits CORS (the server has no reason to allow `localhost:5173` or
 * an Electron `file://` origin for an API-key-gated write endpoint), so this
 * file is a thin hop over IPC rather than a direct request.
 *
 * Fire-and-forget in the sense that it never throws and the caller doesn't
 * have to await it — a failed record shouldn't block or fail the share
 * itself. It DOES resolve with whether it succeeded, though, so a caller
 * that wants to tell the user (e.g. a success toast) can react to that
 * without holding up the rest of the share flow.
 */

export interface RecordSharePayload {
  /** Telemetry id — ties a share back to the device that created it, no more. */
  senderUserId: string;
  /** The share link, exactly as generated by shareLink.ts. */
  longUrl: string;
  /** What the link is about — category name, or the single video's title. Optional. */
  title?: string;
  /**
   * Local shared-list id, when this share is of a list. Lets every recorded
   * row for one list be grouped back together server-side; the main process
   * decides where it lands on the wire (see `shareHandler.ts`).
   */
  listId?: string;
}

/**
 * Tells the backend a share was created. Never throws/rejects — a failure
 * here means the record is lost, not that the share failed; the link the
 * user already has keeps working regardless. Resolves `true`/`false` for
 * callers that want to know the outcome; ignoring the result is fine too.
 */
export const recordShare = async (
  payload: RecordSharePayload,
): Promise<boolean> => {
  if (!window.shareBridge) return false;

  try {
    const result = await window.shareBridge.record(payload);
    return result?.success ?? false;
  } catch (error) {
    // Best-effort only — never surface this to the user as an error.
    console.warn('Failed to record share:', error);
    return false;
  }
};
