import type { Cookie } from 'electron';

export function serializeCookiesToNetscapeJar(cookies: Cookie[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by Downlodr — do not edit',
    '',
  ];

  for (const c of cookies) {
    const includeSubdomains = !c.hostOnly;
    const domain =
      includeSubdomains && !c.domain.startsWith('.') ? `.${c.domain}` : c.domain;
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry =
      c.session || !c.expirationDate ? '0' : String(Math.floor(c.expirationDate));
    lines.push(
      [domain, includeSubdomains ? 'TRUE' : 'FALSE', path, secure, expiry, c.name, c.value].join(
        '\t',
      ),
    );
  }

  return lines.join('\n') + '\n';
}
